
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package evaluacionfinal;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int If = 2;
  public static final int IgualIgual = 6;
  public static final int Parentesis_c = 4;
  public static final int Menor = 7;
  public static final int ERROR = 15;
  public static final int Parentesis_a = 3;
  public static final int EOF = 0;
  public static final int MenorIgual = 9;
  public static final int P_coma = 5;
  public static final int False = 14;
  public static final int Identificador = 11;
  public static final int error = 1;
  public static final int MayorIgual = 10;
  public static final int Mayor = 8;
  public static final int True = 13;
  public static final int Numero = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "If",
  "Parentesis_a",
  "Parentesis_c",
  "P_coma",
  "IgualIgual",
  "Menor",
  "Mayor",
  "MenorIgual",
  "MayorIgual",
  "Identificador",
  "Numero",
  "True",
  "False",
  "ERROR"
  };
}

